name: Build documentation

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    container:
      image: qgis/qgis:3.34
      env:
        QGIS_PLUGIN_IN_CI: 1
        PYTHONPATH: /usr/share/qgis/python/plugins

    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      # - name: Install packages
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install wheel setuptools numpy cython
      #     pip install --no-build-isolation -r requirements.txt
      #     pip install --no-build-isolation -e .

      - name: Install packages
        run: |
          pip install --no-build-isolation -r requirements.txt
      
      - name: Build and deploy docs
        run: |
          python -m doit doc
          python -m mkdocs gh-deploy --force
