name: Build documentation

on:
  workflow_dispatch:
  # push:
  #   branches: [ "master", "ci" ]
  #   paths:
  #     - 'docs/**'

permissions:
  contents: write

jobs:
  build-doc:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-


      - name: Install packages
        run: |
          pip install pypandoc_binary mkdocs mkdocs-material mkdocs-bibtex
      
      - name: Build and deploy docs
        run: |
          python -m mkdocs gh-deploy --force
