on:
  workflow_dispatch:
    
jobs:
  build_linux:

    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install numpy==1.17.4 cython==0.29.33
      - name: Build Cython extension
        run: |
          python -m pip install -e .
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: extension-linux
          path: fct/lib/terrain_analysis.*-linux-gnu.so
          retention-days: 1


  build_windows:
    
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install numpy==1.20.2 cython==0.29.33
      - name: Build Cython extension
        run: |
          python -m pip install -e .
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: extension-windows
          path: fct/lib/terrain_analysis.*-win_amd64.pyd
          retention-days: 1


  release_fct:

    runs-on: ubuntu-latest
    needs: [build_linux, build_windows]

    steps:
      - uses: actions/checkout@v3
      - name: Copy files
        run: | 
          mkdir alien
          cp -r fct alien/FluvialCorridorToolbox
      - name: Download linux build artifact
        uses: actions/download-artifact@v3
        with:
          name: extension-linux
          path: alien/FluvialCorridorToolbox/lib/
      - name: Download windows build artifact
        uses: actions/download-artifact@v3
        with:
          name: extension-windows
          path: alien/FluvialCorridorToolbox/lib/
      - name: Zip release
        run: |
          cd alien
          zip -r -q FluvialCorridorToolbox.zip FluvialCorridorToolbox
      - name: Archive zip artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-zip
          path: alien/FluvialCorridorToolbox.zip
          retention-days: 1
      - name: GitHub release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: alien/FluvialCorridorToolbox.zip
          name: v${{ vars.FCT_CURRENT_VERSION }}
          body_path: CHANGELOG.txt

          