name: 'Run the FCT tests'

description: 'Test all the FCT algorithms and workflows with pytest'

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: qgis/qgis:ltr
      env:
        QGIS_PLUGIN_IN_CI: 1
        PYTHONPATH: /usr/share/qgis/python/plugins
    steps:
      - uses: actions/checkout@v4
      - name: Install fct
        run: |
          python3 -m venv --system-site-packages /env
          /env/bin/python -m pip install -q -r requirements.txt
          /env/bin/python -m pip install --no-build-isolation -q -e .
      - name: Run tests
        run: |
          xvfb-run -s '+extension GLX -screen 0 1024x768x24' /env/bin/python -m pytest -v


