name: Zip plugin for release

on:
  push:
    tags:
      - 'v*'
      
jobs:
  zip-and-release:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Zip release
        run: |
          cp -r fct FluvialCorridorToolbox
          zip -r FluvialCorridorToolbox-${{ github.ref_name }}.zip FluvialCorridorToolbox
        
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: FluvialCorridorToolbox-${{ github.ref_name }}.zip
          draft: true
          generate_release_notes: true
          