name: Zip plugin for release

on:
  workflow_dispatch:
      
jobs:
  zip-and-release:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Zip release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cp -r fct FluvialCorridorToolbox
          zip -r FluvialCorridorToolbox-${{ github.ref_name }}.zip FluvialCorridorToolbox
        
      - name: Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: FluvialCorridorToolbox-${{ github.ref_name }}.zip
          draft: true
          generate_release_notes: true
          