name: Zip plugin for release

on:
  release:
    types: 
      - prereleased
      
jobs:
  zip:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Zip release
        run: |
          cp -r fct FluvialCorridorToolbox
          zip -r FluvialCorridorToolbox-${{ github.event.release.tag_name }}.zip FluvialCorridorToolbox
        
      - name: Attach zip to release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: FluvialCorridorToolbox-${{ github.event.release.tag_name }}.zip
          